version: '3'
services:
  nginx:
    build: build/nginx/
    container_name: nginx
    #ports:
    #  - "80:80"
    depends_on:
      - fpm
      - db
    volumes:
      - /var/log/nginx/:/var/log/nginx/
    networks:
      network-1:
        ipv4_address: 10.0.1.11
    restart: always
  fpm:
    build: build/php/
    container_name: fpm
    volumes:
      - /home/website/mysite/:/var/www/html/site/
    networks:
      network-1:
        ipv4_address: 10.0.1.21
    restart: always
  db:
    image: mysql
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - /home/website/mysite-db/:/var/lib/mysql/
    networks:
      network-1:
        ipv4_address: 10.0.1.31
    restart: always
  memcached:
    image: memcached:latest
    container_name: memcached
    networks:
      network-1:
        ipv4_address: 10.0.1.41
    restart: always

networks:
  network-1:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.1.0/24
