version: '3'
services:
  nginx:
    build: build/nginx/
    container_name: nginx
    depends_on:
      - fpm
      - db
      - memcached
    volumes:
      - /var/log/nginx/:/var/log/nginx/
      - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./conf/nginx/conf.d/:/etc/nginx/conf.d/:ro
      - /home/website/mysite/:/var/www/html/site/
    networks:
      network-1:
        ipv4_address: 10.0.1.11
    restart: always

  fpm:
    build: build/php/
    container_name: fpm
    volumes:
      - /home/website/mysite/:/var/www/html/site/
      - /var/log/php/:/var/log/php/
      - ./conf/php/php.ini:/usr/local/etc/php/php.ini:ro
#      - ./conf/php/fpm.pool.d/domain.conf:/usr/local/etc/php-fpm.d/domain.conf:ro
    networks:
      network-1:
        ipv4_address: 10.0.1.21
    restart: always
    cap_add:
      - SYS_NICE
      - DAC_READ_SEARCH

  db:
    image: mysql
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - /home/website/mysite-db/:/var/lib/mysql/
      - /var/log/mysql/:/var/log/mysql/
      - ./conf/mysql/:/etc/mysql/conf.d/:ro
    networks:
      network-1:
        ipv4_address: 10.0.1.31
    restart: always

  memcached:
    image: memcached:latest
    container_name: memcached
    networks:
      network-1:
        ipv4_address: 10.0.1.41
    restart: always

networks:
  network-1:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.1.0/24
